### ISSUE TITLE
Duplicate ckeditors with Sonata Admin Boundle (sonata_type_collection)

### ISSUE THREAD

**Issue by aivus** [egeloen/IvoryCKEditorBundle#140]
This can be hard fixed with:
`setTimeout(function(){CKEDITOR.replace("%s", %s);}, 10);` in CKEditorHelper::renderReplace

But i'm not sure that is the problem of this boundle.

![image](https://cloud.githubusercontent.com/assets/1021703/5488695/1086754e-86ca-11e4-92b5-3ed27027546a.png)

**Comment by informatico-madrid** [comment]
Hi, i have same issue and i not use SonataAdminBundle. I have the issue only inside form collection.
