### ISSUE TITLE
Invalid version string "^2.0.5"

### ISSUE THREAD

**Issue by truckee** [egeloen/IvoryCKEditorBundle#142]
Attempting to install symfony-cmf results in 

>   [RuntimeException]
>   Could not load package egeloen/ckeditor-bundle in http://packagist.org: [Un
>   expectedValueException] Could not parse version constraint ^2.0.5: Invalid
>   version string "^2.0.5"

Due to line 23 in composer.json: `"symfony/yaml": "^2.0.5",`?

**Comment by ramcorreio** [comment]
Hello,

I have the same problem and my composer is latest version. Somebody helps me?

**Comment by egeloen** [comment]
Can you give me the version of your composer install? IMO, you're not using the latest version of composer since it is a supported feature.

**Comment by ramcorreio** [comment]
root@packs:~# php /var/www/www/remote/bin/satis build /var/www/www/remote.json /var/www/www/remote/web
Scanning packages



  [RuntimeException]
  Could not load package egeloen/ckeditor-bundle in https://packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.0.5: Invalid ver
  sion string "^2.0.5"






  [UnexpectedValueException]
  Could not parse version constraint ^2.0.5: Invalid version string "^2.0.5"



build [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]


root@packs:~# composer --version
Composer version 1.0-dev (0662036f5ebc0bd33b4300fa68c3263c5e4ef584) 2015-01-11 23:38:42

**Comment by egeloen** [comment]
I see your using Satis. I'm not sure the caret feature has been backported. Can you open an issue on Satis at it seems related to it.

**Comment by ramcorreio** [comment]
wow!!! 
Now, thats ok.
Thanks a lot
