### ISSUE TITLE
json-builder conflict composer

### ISSUE THREAD

**Issue by Bersman** [egeloen/IvoryCKEditorBundle#147]
Hi,
I wanted to upgrade from ~2.0 to ~3.0
But I get the following error from composer:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: egeloen/json-builder[2.0.0, 1.0.3].
    - Can only install one of: egeloen/json-builder[2.0.0, 1.0.3].
    - egeloen/ckeditor-bundle 3.0.0 requires egeloen/json-builder ~2.0 -> satisfiable by egeloen/json-builder[2.0.0].
    - Installation request for egeloen/ckeditor-bundle ~3.0 -> satisfiable by egeloen/ckeditor-bundle[3.0.0].
    - Installation request for egeloen/json-builder == 1.0.3.0 -> satisfiable by egeloen/json-builder[1.0.3].

Setting:
"egeloen/json-builder": "~2.0",
or
"egeloen/json-builder": "~1.0",

won't help. Because something needs 1.0.3 and something needs 2.0.0
Any suggestions to solve this?

For the info: I'm using: "helios-ag/fm-elfinder-bundle": "~3.2" too.

**Comment by egeloen** [comment]
@Bersman Very good question!... What is the package which requires the `1.x` version of the json-builder? AFAIR, the `helios-ag/fm-elfinder-bundle` does not require explicitely either the ckeditor bundle or the json builder.

**Comment by Bersman** [comment]
Found the problem. With update "egeloen/ckeditor-bundle" the old 1.0.3 in the composer.lock was not removed. So that was causing problems because it was "required" in the .lock file. Removing that and it works :)
Sorry and thanks for your time.

**Comment by egeloen** [comment]
You're welcome!
