### ISSUE TITLE
Required attribute

### ISSUE THREAD

**Issue by Jogrin** [egeloen/IvoryCKEditorBundle#148]
First of all i want to thank you for your great job :)
I have some problem with the html5 required attribute.
I initialize the form builder with the 'required' => true parameter but it doesn't work.. making useless the browser validation.
The only way is with jquery validation or other similar tools?
Here my portion of code:

$builder->add('fieldName', 'ckeditor', array(
                    'required' => true, <-- here the param
                    'config' => array(
                        'toolbar' => array(
                        ),
                        'uiColor' => '#ffffff',
                        'resize_enabled' => false,
                        'removePlugins' => 'elementspath',
                        'height' => '60px',
                        'width' => '100%',
                        'extraPlugins' => 'wordcount',
                        'wordcount' => array(
                            'showWordCount' => false,
                            'showCharCount' => true,
                            'countHTML' => false,
                            'charLimit' => 50,
                            'countSpacesAsChars' => true,
                        )
                    ),
                ))

Thanks

**Comment by egeloen** [comment]
Hum, that's strange, according to http://dev.ckeditor.com/ticket/8031 the bug should be fixed. Does the textarea have the `required` attribute enabled?

**Comment by Jogrin** [comment]
the attribute isn't present.. i use the 3.0.0 (stable) version of the bundle.

**Comment by Jogrin** [comment]
I've tried also to render the field (in twig) with "required" attribute
{{ form_row(form.field, {'attr': {'required': "true"} }) }}
it seem that the attribute is ignored :)

**Comment by egeloen** [comment]
AFAIR, the `attr` attributes are rendered by the `widget_attributes` block.I just check the template and this block is still here so, it should be rendered. Are you sure, you don't override any form block which could end up with this strange behavior?

**Comment by egeloen** [comment]
Btw, what's your Symfony vesion?

**Comment by Jogrin** [comment]
I'm using the standard form template (no override, no implementation).
Here my steps:
Create bundle -> install (through composer) library and activate -> create form type -> render form inside twig.
Symfony version: 2.5.9 (updated two days ago)

**Comment by Jogrin** [comment]
Strange behaviour... i've tried to print "{{ block('widget_attributes') }}" inside the textarea (where the statement "{{ value }}" is located) and the "required" attribute is present:
id="..." name="..." required="required"

**Comment by egeloen** [comment]
I just check and the required is well printed in my [fork](https://github.com/egeloen/symfony-standard/tree/ckeditor). Can you try to reproduce your issue from this specific branch?

**Comment by Jogrin** [comment]
[Here](https://github.com/Jogrin/symfony-standard/tree/ckeditor)  i reproduce the issue using your branch.
Effectively the attribute is present.. but it doesn't work cause you can submit the form without any errors..
It seems the problem is the ckeditor library, not your bundle.
What do you think? :)

**Comment by egeloen** [comment]
I'm not sure maybe there is something to enable in the config in order to get the validation working. I'm not a CKEditor expert at all... Anyway, at this state, I would open ticket on the CKEditor bug tracker as the required flag seems handled by CKEditor (it is removed from the dom) but then, no validation is done before submitting.

**Comment by Jogrin** [comment]
you're right .. will manage everything with jQuery ( :/ ).
sorry for wasting your time :)

**Comment by AchirAdelMounir** [comment]
Ⓜ️
