### ISSUE TITLE
Oembed plugin integration

### ISSUE THREAD

**Issue by jiboule** [egeloen/IvoryCKEditorBundle#154]
Hello !

First of all, thank you for this bundle and the work you've done.

I'm having troubles to install a plugin in my ckeditor field; in my form builder i have :

$formBuilder->add('content', 'ckeditor', array(
    'plugins' =>  array(
        'oembed' => array(
            'path'     => '/ckeditor/plugins/oembed/',
            'filename' => 'plugin.js',
        ),
    )
));

I put the ckeditor/plugin/oembed in the web folder

Sadly, nothing is happenning, I have no error, the field is displayed but without the plugin. If I try to add the plugin in my toolbar it changes nothing.

Any idea of what i'm doing wrong ?

(symfony 2.5)

**Comment by egeloen** [comment]
Sorry for the delay but I'm really busy at work... Can you fork my Symfony SE and reproduce your issue? Then, I would be able to play with your branch and get the exact same behavior.

**Comment by jiboule** [comment]
My turn to appologize, I managed to install the plugin thanks to this issue : https://github.com/egeloen/IvoryCKEditorBundle/issues/97 

Sorry for the inconvenience !
