### ISSUE TITLE
Conflict with IvoryGoogleMapBundle

### ISSUE THREAD

**Issue by Julien-Webgenery** [egeloen/IvoryCKEditorBundle#155]
Hello, 

I met a conflict when i was trying to install last stable version of IvoryCKEditorBundle and IvoryGoogleMapBundle on the same project.
IvoryCKEditorBundle(3.0.0) require "egeloen/json-builder": "~2.0",
IvoryGoogleMapBundle(1.4.1) require "egeloen/google-map": "~1.4.0" which require "egeloen/json-builder": "~1.0.0"
So composer send me an error : Can only install one of: egeloen/json-builder[2.0.0, 1.0.3]

I have been forced to downgrade IvoryCKEditorBundle to 2.5 to instal my project

**Comment by egeloen** [comment]
I will release a new version which supports both, the 2.x and the 3.x as there is not API BC breaks.
