### ISSUE TITLE
How to define  maxFilesize limit for CKEditor uploads?

### ISSUE THREAD

**Issue by dmarko484** [egeloen/IvoryCKEditorBundle#165]

**Comment by egeloen** [comment]
If you can point me the related CKEditor property in the CKEditor doc I would be able to help you. (I don't have time to search it).

**Comment by egeloen** [comment]
AFAIR, the way to implement upload with CKEDitor in a Symfony2 context is to handle by yourself the upload in a dedicated controller as explain in the [doc](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/file_browse_upload.md). So, it is the same way as it is in PHP itself.
