### ISSUE TITLE
The CKEditor example usage code doesn't work 

### ISSUE THREAD

**Issue by txsing** [egeloen/IvoryCKEditorBundle#170]
I have installed the IvoryCKEditorBundle following the instruction (Symfony 2.6)
However the following code doesn't work 

#Form/TestEditor
<?php
namespace Blogger\BlogBundle\Form;
use Doctrine\ORM\Mapping\ClassMetadata;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Ivory\CKEditorBundle\IvoryCKEditorBundle;

class TestEditor extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('field', 'ckeditor', array(
            'config' => array(
                'toolbar' => array(
                    array(
                        'name'  => 'document',
                        'items' => array('Source', '-', 'Save', 'NewPage', 'DocProps', 'Preview', 'Print', '-', 'Templates'),
                    ),
                    '/',
                    array(
                        'name'  => 'basicstyles',
                        'items' => array('Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'),
                    ),
                ),
                'uiColor' => '#ffffff',
            ),
        ));
    }

#Controller
    public function editAction()
    {
        $form    = $this->createForm(new TestEditor());
        return $this->render('BloggerBlogBundle:Blog:editblog.html.twig',array(
            'form' =>$form->createView()
        ));
    }

#The result
![screen shot 2015-05-18 at 15 10 33](https://cloud.githubusercontent.com/assets/7507377/7675868/25b315d6-fd70-11e4-855b-a05f5ed07d92.png)

**Comment by txsing** [comment]
#Template
 <form action="{{ path('BloggerBlogBundle_blog_create' ) }}" method="post" {{ form_enctype(form) }} class="blogger">
            {{ form_widget(form) }}
            <p>
                <input type="submit" value="Submit">
            </p>
        </form>

**Comment by txsing** [comment]
#Template 
![screen shot 2015-05-18 at 15 14 55](https://cloud.githubusercontent.com/assets/7507377/7675917/cc78032c-fd70-11e4-8570-866a9be67a06.png)

**Comment by egeloen** [comment]
Have you install the assets via `php app/console assets:install web`

**Comment by txsing** [comment]
Problem solved, thank you for your kind remind!
