### ISSUE TITLE
Set textarea attribute with ckeditor

### ISSUE THREAD

**Issue by InternalServerError** [egeloen/IvoryCKEditorBundle#175]
Hi,

First of all, thanks for your bundle which works good :)
However, I'd like to set defaults attributes of my ckeditor textarea like "label", "cols" and others wich set before on a basic textarea element symfony form.
I tried to : `array('label'=>'MyLabel', 'attr'=>array('class' => 'myName', 'ligne'=>1,'colonne'=>2,'colspan'=>3, 'cols'=>50))) ` in 'config' array or before the config definition but in vain.
What is the way for implement it please ?

Thanks by advance,
ISE.

**Comment by egeloen** [comment]
Hum, are you saying that the following does not work?

``` php
$builder->add('my_field', 'ckeditor', array(
    'label' => 'label', 
    'attr' => array(
        'class' => 'myName', 
        'ligne' => 1,
        'colonne' => 2,
        'colspan' => 3, 
        'cols' => 50,
    ),
));
```

**Comment by cordoval** [comment]
@InternalServerError ping

**Comment by egeloen** [comment]
@InternalServerError ping

**Comment by egeloen** [comment]
Closing as I just test it and everything works as expected and there is no actvity from the reporter.
