### ISSUE TITLE
Can i set path to html file instead of raw html in config.yml?

### ISSUE THREAD

**Issue by khronedev** [egeloen/IvoryCKEditorBundle#180]
Hi,

To define a template i use the config.yml way:

    templates:
                -
                    title:       "My Template"
                    image:       "image.jpg"
                    description: "My awesome template"
                    html:        "<p>Crazy template :)</p>"

But here is `html` parameter - can i use a path to html file instead? I hate the idea of putting HTML code into config files, it's hard to edit and so ugly. Supporting twig (so i can specify .html.twig file) would also be nice :) I hope, that, maybe it's just not documented.

Cheers

**Comment by egeloen** [comment]
Currently this is not supported. The template rendering is done [here](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Templating/CKEditorHelper.php#L166), so we can maybe inject the twig engine in the helper and then render the template if the html node is a twig template.

**Comment by khronedev** [comment]
I've written small gulp script to help me with this task. It's not great - but is working. Kind of hack :)
```javascript
var gulp = require('gulp');
var gutil = require('gulp-util');
var intercept = require('gulp-intercept');
var replace = require('gulp-replace');
var minifyHTML = require('gulp-minify-html');

gulp.task('ckeditor:generate', function(){
    var minifyOptions = {};

    return gulp.src('./web/' + assetsSourceFolder + '/ckeditor_templates/*.html')
        .pipe(minifyHTML(minifyOptions))
        .pipe(intercept(function(file){
            var nameWithExtension = file.path.split('/')[file.path.split('/').length - 1];
            var name = nameWithExtension.split('.')[0];

            gutil.log('Replacing config (\"app/config/config.yml\") for template \"' + name + '\"');

            var configToFind =  new RegExp('#                   source_name: __TEMPLATE_' + name + '__\n                    html: (.+)');
            var configToPush =  '#                   source_name: __TEMPLATE_' + name + '__\n' +
                                '                    html:        \'' + file.contents.toString() + '\'';

            gulp
                .src('app/config/config.yml')
                .pipe(replace(configToFind, configToPush))
                .pipe(gulp.dest('app/config/'));
        }));
});
```
What is does - it's just find & replace:
1. Get content of HTML file and minify it.
2. Find a sequence in ````config.yml```` like:
```
#                   source_name: __TEMPLATE_description_book__
                     html:                'some text'
```
3. And replace the value of "html" section to the minified content of HTML file. The name of the file is an ID: ````__TEMPLATE_<filename>__````

Maybe someone will save some time using this :) I did.

Cheers
