### ISSUE TITLE
CKeditor replaces all contanteditable=true tags

### ISSUE THREAD

**Issue by spin7ion** [egeloen/IvoryCKEditorBundle#182]
You should add option for it and add CKEDITOR.disableAutoInline=true in view

**Comment by egeloen** [comment]
Can you elaborate? I maintain the bundle but I'm not a CKEditor expert :) (just one which have read some part of the doc)

**Comment by egeloen** [comment]
ping @spin7ion

**Comment by egeloen** [comment]
Your issue has been fixed in 6b7eb55
