### ISSUE TITLE
Duplicate toolbars items from multiple config

### ISSUE THREAD

**Issue by Benschumi74** [egeloen/IvoryCKEditorBundle#183]
Hello,

I have a bundle which is children of a bundle parent.

I put the ckeditor config in the parent bundle but some time i need to override it from the children like many other symfony bundle.

If i have two items from toolbars with the same name, the toolbar is merged and not overrided.

For exemple, the following config is in the parent and child bundle
<pre><code>
indentation: ['Outdent','Indent' ]
</code></pre>

The following picture can help to understand

![prtscr capture_670](https://cloud.githubusercontent.com/assets/8670015/9688260/56275808-532e-11e5-8b15-ffbe5b210a6b.jpg)

Is this a bug or not?
Can you add an option for override and not merge the config?

Thank you

**Comment by egeloen** [comment]
Sorry but I have not understood (especially the part `I put the ckeditor config in the parent bundle`). The condif is part of the application not part of a bundle. Can you re-explain in a different way?

**Comment by Benschumi74** [comment]
Bonjour,

Je vois que vous êtes français donc je vous réponds par mail en français ça
sera plus simple.

Pour schématiser, nous avons :


   - une application *logiciel *dans un package qui contient différent
   bundle.
   - une application *moteurs de site* dans un package qui contient
   différent bundle qui sont pour la plupart enfant des bundle de
   l'application logiciels.
   - plusieurs applications *site *dans des packages qui contiennent
   différent bundle qui sont pour la plupart enfant des bundle de
   l'application moteur de site

Nous utilisons IvoryCKEditorBundle dans cet environnement, il est utilisé
dans le *logiciel *mais est configuré au niveau des applications *sites*.
Récemment nous avons voulu mettre une configuration "générique" au niveau
de l'application *logiciel *mais on dirait que la configuration fusionne au
lieu d'être surchargé au niveau des toolbars.

Nous avons un config.yml dans *site *qui surcharge les entrées du
config *moteurs
de site*, qui lui surchargent ceux de logiciel, qui surchargent celui dans
le app/config.

J'espère avoir été clair.

Merci


2015-09-04 18:27 GMT+02:00 Eric GELOEN <notifications@github.com>:

**Comment by cordoval** [comment]
please write in english @Benschumi74

**Comment by Benschumi74** [comment]
If you want to redefine part of the config of IvoryCKEditorBundle in another config file, It doesn't overwrite, it merge.

For example if i have this in a bundle config in vendor or src
<pre>
<code>
ivory_ck_editor:
  toolbars:
    configs:
      contenu_dynamique: [ "@document","@clipboard","@alignement" ]
    items:
      document: [ 'NewPage','Preview','Print','-','Templates' ]
      clipboard: [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ]
      alignement: [ 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
</code>
</pre>

And i want to overwrite "contenu_dynamique" toolbar and "clipboard" item in config of app directory
<pre>
<code>
ivory_ck_editor:
  toolbars:
    configs:
      contenu_dynamique: [ "@clipboard","@alignement" ]
    items:
      clipboard: [ 'Cut','Copy','Paste']
      alignement: [ 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
</code>
</pre>

Normally i expect this

![prtscr capture_709](https://cloud.githubusercontent.com/assets/8670015/9960019/4d4ef46c-5e18-11e5-8f97-d73faee9d771.jpg)

But here the result 

![prtscr capture_710](https://cloud.githubusercontent.com/assets/8670015/9960068/b2c7c30a-5e18-11e5-9711-1b58240de538.jpg)


my config compilated by symfony would be something like 

<pre>
<code>
ivory_ck_editor:
  toolbars:
    configs:
      contenu_dynamique: [ "@document","@clipboard","@alignement","@clipboard","@alignement" ]
    items:
      document: [ 'NewPage','Preview','Print','-','Templates' ]
      clipboard: [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo','Cut','Copy','Paste' ]
      alignement: [ 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
</code>
</pre>


Is this normal or an issue ?
If this is normal can you add a parameter in your config for overwrite instead of merge?

Thank you

**Comment by egeloen** [comment]
This is maybe a bug indeed. Let me try something and I will ping you back here.

**Comment by egeloen** [comment]
In fact my solution will fix an other issue :s I'm not sure but here, we are facing a Symfony limitation. I don't think I will be able to control how Symfony merge Yaml file coming from different places...

**Comment by egeloen** [comment]
Hum, so after re-reading the doc, we can maybe rely on `[performNoDeepMerging](http://symfony.com/fr/doc/current/components/config/definition.html#options-de-fusion)` when building the configuration but I don't know how to make it conditional according to an other param.

**Comment by egeloen** [comment]
@Benschumi74 Have you found a solution to your issue?

**Comment by egeloen** [comment]
Closing as there is not activity and it seems something we can't fix in the bundle.
