### ISSUE TITLE
plugins path configuration

### ISSUE THREAD

**Issue by perie** [egeloen/IvoryCKEditorBundle#185]
Hello, I tried to add a plugin in my CKEditor but it only work if I put the module folder into the web/bundles/ivoryckeditor/plugins/ folder.
The problem is after all my assets:install they be deleted.

I try to put it in a module folder /bundles/myckeditor/plugins/htmlbuttons/
Here the configuration : 

ivory_ck_editor:
    plugins:
        htmlbuttons:
            path:     "/bundles/touchmodsckeditor/plugins/htmlbuttons/"
            filename: "plugin.js"

In JS console i can read this error : 
10:12:09,521 uncaught exception: [CKEDITOR.resourceManager.load] Resource name "htmlbuttons" was not found at "http://local.dropy.com/bundles/ivoryckeditor/plugins/htmlbuttons/plugin.js?t=E8PB".1 <inconnu>

**Comment by egeloen** [comment]
What do you mean by `The problem is after all my assets:install they be deleted.`?

**Comment by egeloen** [comment]
Btw, have you enable it in your config?

**Comment by perie** [comment]
@egeloen : When I do assets:install, the plugins folder i put on the /bundles/ivoryckeditor/plugins/htmlbuttons, they are deleted by the command assets:install.

When i do the configuration like specified in a previous post, the ckeditor only work if i put the plugins folder in the /bundles/ivoryckeditor/plugins/

**Comment by Infernosquad** [comment]
I have the same problem here even after reinstalling assets and clearing cache:

My config:

```yaml
ivory_ck_editor:
    default_config: cmf_config
    plugins:
        media:
            path:     "/vendor/ckeditor/plugin/media/"
            filename: "plugin.js"
    configs:
        cmf_config:
            toolbar: ~
            extraPlugins: media
```
Uncaught [CKEDITOR.resourceManager.load] Resource name "media" was not found at "http://localhost:8000/bundles/ivoryckeditor/plugins/media/plugin.js?t=E8PB".

**Comment by egeloen** [comment]
Hum, can you give me a link where I can download your plugin? and the exact configuration you use in order to reproduce it?

**Comment by alexandrebodin** [comment]
Yep that's a real issue.

The path configuration for plugins isn't used. 
Ckeditor tries to load plugins and icons et stuff with it's basePath configuration. 

And it is set at /bundles/ivoryckeditor/plugins.

You might consider using CKEDITOR.plugins.addExternal( 'sample', '/myplugins/sample/' );

**Comment by egeloen** [comment]
Can someone explain me why this branch is working well whereas it seems there is missing CKEditor configuration according to your comments?

**Comment by diegoleft** [comment]
Hey @egeloen 
I think im having a similar problem, i will try to explain in detail to you understand.

1) I add the plugin **wordcount** in config.yml
```
plugins:
        wordcount:
            path:     "/bundles/mybundle/wordcount/"
            filename: "plugin.js"
```
2) I call the pluging in the form
```
'config' => array(
                        'extraPlugins' => 'wordcount',
                    ),
```
3) I go to my localhost to check the if the pluging works and i received this log in the console

*Resource name "notification" was not found at "bundles/ivoryckeditor/plugins/notification/plugin.js?t=F0RD"*

This means the wordcount requires the **notification** pluging and is looking for that in **ivoryckeditor** folder, Then I copypaste the folder of Notification Pluging inside the folder "bundles/ivoryckeditor" and works.

But the problem is when I delete the cache that deletes the folder too, because doesn´t exists in the vendor.

4) The solution i think is add a new parameter in the config.yml to look for the require plugins for example **Notification Pluging** who is required for **Wordcount pluging** in the path of this new variable of config.yml or in the same bundle folder where is our wordcount pluging. (in my case ´bundle/mybundle/´)

I think the guys abobe are having the same problem, that is because the pluing.js of each pluging ask for another plugins in the vendor (sometimes with the same name) and doesn´t exists in the vendor

Let me know if this is clear. or if someone already solved this problem

**Comment by alexandrebodin** [comment]
The best solution I came up with is to configure the bundle to load your plugins from you bundle's assets and instead of letting ckeditor do an ajax call to get the plugin load it by hand as follows: 

```javascript
CKEDITOR.plugins.addExternal( 'plugin_name', '/ckeditor/plugins/plugin_name/', 'plugin.js' );

```

**Comment by welcoMattic** [comment]
@egeloen,

I think the problem here is that we cannot load our own plugins (specially those already in your bundle) and there dependancies.

Example today:

I've try to load `image2` plugin from my own `web/ckeditor_extra_plugins` folder because `image2` plugin requires `widget` plugin and `widget` plugin is not included in your bundle.

The best way to fix this problem would be to allow developers to load there own plugins, dependancies included.

**Comment by ju1ius** [comment]
Hi,
Not 100% related to this issue, but I found out that the Symfony Config component messes names up !
Given I have a plugin named 'my-plugin'
And the following configuration:

```yaml
# app/config.yml
ivory_ck_editor:
    plugins:
        my-plugin:
            path: /assets/cke/plugins/my-plugin/
            filename: plugin.js
    configs:
        my_config:
            extraPlugins: 'my-widget'
```
The ckeditor config output will be:
```js
CKEDITOR.plugins.addExternal('my_plugin', '/assets/cke/plugins/my-plugin/', 'plugin.js');
```
Notice [the difference](http://symfony.com/doc/current/components/config/definition.html#normalization) ?
> The normalization process is used to remove some of the differences that result from different configuration formats, mainly the differences between YAML and XML.
> The separator used in keys is typically _ in YAML and - in XML. For example, auto_connect in YAML and auto-connect in XML. The normalization would make both of these auto_connect.

> The target key will not be altered if it's mixed like foo-bar_moo or if it already exists.

So I guess a good move would be to add a "name" key for the plugin config that can be safely used to reference the plugin in javascript.

```php
// IvoryCKEditorBundle/DependencyInjection/Configuration.php
/**
 * Creates the plugins node.
 *
 * @return \Symfony\Component\Config\Definition\Builder\NodeDefinition The plugins node.
 */
private function createPluginsNode()
{
    return $this->createNode('plugins')
        ->useAttributeAsKey('id')
        ->prototype('array')
            ->children()
                ->scalarNode('name')->end()
                ->scalarNode('path')->end()
                ->scalarNode('filename')->end()
            ->end()
        ->end();
}
```

**Comment by egeloen** [comment]
@ju1ius Can you open a separate issue for your bug as indeed, these keys should not be normalized by the config component.

For the others, I will give a try to this issue right now.

**Comment by egeloen** [comment]
So, after debugging it, I still don't see an issue in the current implementation (except for the key normalization) :s

Here, the diff of the 2.8 symfony-standard brand againt a working installation of the wordcount plugin.

So, to resume the process:

 - FIrst step: I have downloaded the latest wordcount plugin at http://ckeditor.com/addon/wordcount and put it in the public directory of the `IvoryCKEditorDemoBundle`. Then, I have installed it in the web directory via the `assets:install` symfony command.

 - Second step: I have configured the bundle to use it in the `plugins` node and in the `extraPlugins` of the config node.

At this state, a simple plugin without dependency works. On my laptop, the plugin is well located at the path configured without trouble.

For @perie, according to your description, I think you have not followed the first step of the process I just described.

For @alexandrebodin The `CKEDITOR.plugins.addExternal` is already implemented and used (See https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Templating/CKEditorHelper.php#L126-L134), so I don't understand why you're saying that the plugin registering is not done. Isn't it rendered in your view?

Now, this part is for @diegoleft and @welcoMattic, according to the CKEditor doc, after installing it, we also need to "Download and configure all its dependencies, too." Basically, there is no magic and it's the same in the bundle. You need to install/configure its dependencies as you have done for the base plugin. If it is shipped with the bundle, nothing to do but if it is not, then no choice, we need to redo the process.

**Comment by egeloen** [comment]
I come back here as I just give a try to the wordcount/codesnippet plugins and everything is working as expected... Here the branch for from the Symfony SE: symfony/symfony-standard@master...egeloen:ckeditor-plugin

The sreenshot of the working plugins:

![ckeditor](https://cloud.githubusercontent.com/assets/737992/11762794/35891f56-a0f3-11e5-9d87-23f86c06107b.png)

The main point to understand is if you add extra plugins to the bundle, you must configure all its dependencies. An alternative is to use the CKEditor online builder and use your own version of CKEditor with everything packaged.

**Comment by StrikeForceZero** [comment]
I've been working with the [SonataFormatterBundle](sonata-project/SonataFormatterBundle)
and was banging my head against the wall with this issue. Thanks to the clean room example provided above, I was able to determine the bundle was doing something preventing this.

I'm still investigating, but for now it seems to be working with [this commit](5bf73ec86c212ebc39ad057ab1ecb511e2cdbffc). Hopefully that saves anyone's time that comes across this issue using that bundle and saves @egeloen from being blamed.

**Comment by famas23** [comment]
i dowloaf my ckeditor from http://ckeditor.com/builder and i extract it into "web/bundles/sonataformatter" folder.
Any one find a solution for the problem please help ????this my code:
ivory_ck_editor:

    default_config:  news
    configs:
        news:
            
            extraPlugins: "codesnippet"
            language: %locale%
            toolbar: standard 
            stylesSet: "my_styles"
            uiColor: "#FCFCFC" #Couleur de fond de l'interface
            height: '600px' #Hauteur par défaut
            contentsCss: ['bundles/app/css/style.css']
    plugins:
        codesnippet:
            path:       "/bundles/sonataformatter/vendor/ckeditor/plugins/codesnippet/"
            filename:   "plugin.js"


and i got this js error message :
http://localhost/sandbox-build-2.4/web/bundles/sonataformatter/vendor/ckeditor/plugins/codesnippet/plugin.js?t=E4KA".

-------------------------------------------------------------------------------------------------

**Comment by compains** [comment]
@StrikeForceZero I had same issue. I was using this bundle with SonataFormatterBundle. After updating bundles it's working properly.

**Comment by santasachin** [comment]
Hi any one know about how to integrate live collabrate plugin in ck-editor.
I tried but i can't do this.Anyone Helpme please...
