### ISSUE TITLE
Ckeditor stripping empty i tags

### ISSUE THREAD

**Issue by raul782** [egeloen/IvoryCKEditorBundle#188]
Is there a way to stop CKEditor to strip an empty i tag element.

I've seen this type of config that can be applied directly on the config file.
CKEDITOR.dtd.$removeEmpty['i'] = false

However, how can this be translated with this bundle?

**Comment by egeloen** [comment]
Currently, this is not supported, you wan't update the `dtd` directly. Anyway, you can override the form theme of the bundle and do what you want in the `ckeditor_widget` block.

**Comment by egeloen** [comment]
An other solution is to use form extension as described here: https://symfony.com/doc/current/cookbook/form/create_form_type_extension.html

Then, you can easily manage your own option an manipulate the dtd according to them. 

If you find a way to manage the dtd in a generic way, I'm :+1: for adding it to the bundle.
