### ISSUE TITLE
add codesnippet plugin troubles

### ISSUE THREAD

**Issue by podisto** [egeloen/IvoryCKEditorBundle#191]
Hi i try to add codesnippet plugin to Ckeditor http://ckeditor.com/addon/codesnippet i follow your instructions according to add plugin but my textarea doesn't appear after that. If i remove plugin it's work again. What i have missed in the config node ?

**Comment by podisto** [comment]
Here is my config 
`
#IvoryCkeditor Config
ivory_ck_editor:
    default_config: my_custom_config
    configs:
        my_custom_config:
            extraPlugins: "codesnippet"
            language: %locale%
            toolbar: standard # Charger la toolbar toolbar_1 (plus bas)
            stylesSet: "my_styles" # Chargement des styles personnalisables
            uiColor: "#FCFCFC" #Couleur de fond de l'interface
            height: '600px' #Hauteur par défaut
            contentsCss: ['bundles/app/css/style.css']
    plugins:
        codesnippet:
            path:       "/bundles/blog/codesnippet/"
            filename:   "plugin.js"
`

**Comment by egeloen** [comment]
Is there JS error in your browser console?

**Comment by podisto** [comment]
i have any JS error ! Finally i use CKBuilder and add the plugins and skin i need and its works! thank

**Comment by egeloen** [comment]
OK, nice to see you have found a workaround. Anyway, can you let this issue open in order I investigate what going wrong with this plugin later. It seems related to #185 at first read...

**Comment by podisto** [comment]
okey! it's seem this is a recurrent error.

**Comment by egeloen** [comment]
Yes, it needs more investigation. The last time I debug it, it worked as expected but I have not try this specific plugin. Maybe there is an issue but for now, I have still not spotted it.

**Comment by podisto** [comment]
ok i will follow next branch! thanks

**Comment by egeloen** [comment]
I come back here as I just give a try to the codesnippet plugin and everything is working as expected... Here the branch for from the Symfony SE: https://github.com/symfony/symfony-standard/compare/master...egeloen:ckeditor-plugin

The sreenshot of the working plugins:

![ckeditor](https://cloud.githubusercontent.com/assets/737992/11762769/9386fe62-a0f2-11e5-9b66-e8d1f6eb820f.png)

The main point to understand is if you add extra plugins to the bundle, **you must configure all its dependencies**. An alternative is to use the CKEditor online builder and use your own version of CKEditor with everything packaged.

**Comment by podisto** [comment]
"The main point to understand is if you add extra plugins to the bundle, you must configure all its dependencies" may be this is what's wrong with me :+1:

**Comment by famas23** [comment]
@podisto can u provide me u'r source code , i got the same problem can u tell me where i set my ckeditor files and how to config the path and file name in the ivory_ck_editor .

**Comment by podisto** [comment]
Hi @famas23, u can fork [this repository](https://github.com/podisto/openwecco) and dive into app/Resources directory. U'll see all configuration i have used.
