### ISSUE TITLE
Placeholder inside ckeditor

### ISSUE THREAD

**Issue by JHGitty** [egeloen/IvoryCKEditorBundle#195]
Is it possible to have a placeholder inside the ckeditor like on a 'text' or 'textarea' field?

**Comment by egeloen** [comment]
If you can point me the way it should be with CKEditor in their docs, I should be able to explain you how to do it with the bundle.

**Comment by JHGitty** [comment]
Oh.. I just found this: http://alfonsoml.blogspot.com.es/2012/04/placeholder-text-in-ckeditor.html

**Comment by egeloen** [comment]
Ok, so it shoudl already be supported using:

``` php
$builder->add('field', 'ckeditor', ['attr' => ['placeholder' => 'Type here']]);
```

Isn't it?

**Comment by egeloen** [comment]
Hum, after googling it, it seems not supported natively by CKEditor, you need to use a plugin: http://ckeditor.com/addon/confighelper and combine it with the html5 placeholder.
