### ISSUE TITLE
Could not load type "ckeditor" after update to 4.0.0

### ISSUE THREAD

**Issue by MartinLyne** [egeloen/IvoryCKEditorBundle#197]
Hi,
 I just updated my working version to version 4.0.0 and now I cannot use the ckeditor widget. 

I've tried:
 - Running composer update again, just in case
 - Assetic install, assetic dump
 - Cache clear
 - Confirmed bundle is registered still
 - Gone over installation instructions again

I'll roll back to version 3 for now, but just thought I'd mention it!

**Comment by egeloen** [comment]
Thanks for reporting! What is your Symfony version?

**Comment by MartinLyne** [comment]
Symfony 2.7.6 
PHP 5.5.9-1ubuntu4.14

If you need any other info just let me know :)

**Comment by egeloen** [comment]
@MartinLyne Can you give a try to the referenced PR?

**Comment by egeloen** [comment]
I just merge the patch and also release 4.0.1.
