### ISSUE TITLE
Can't dynamically add ckeditor to fields 3.0.1

### ISSUE THREAD

**Issue by MartinLyne** [egeloen/IvoryCKEditorBundle#198]
Hi,
 I feel like I'm being really dumb right now. 

Here's my config:

    ivory_ck_editor:
        default_config: "basic"
        jquery: true
        autoload: true
            configs:
                basic:
                    toolbar: [[ "SpellChecker", "Undo", "Redo"], ["Bold", "Italic", "NumberedList"], ["Link", "Unlink"],["Find", "Replace"]]

CKEditor appears just fine for a widget in a form, but if I try to use javascript to enable it in the console, for instance, using either method:

- `$('#thing').ckeditor()` yields "ckeditor is not a function"

- `CKEDITOR.replaceAll('className')` returns undefined in console and does nothing on page (no errors)

- `CKEDITOR.replace('className')` returns an error: `Uncaught TypeError: Cannot read property 'getEditor' of undefined` that's line 316 of the minified version (trying to checkif it already has an editor but a is not found? there are things with that class name if I use jquery selector)

Tried on pages with and without an existing ckeditor form field, no luck.

I don't know what else to try! Thanks for any help.

**Comment by MartinLyne** [comment]
Here's my JS files, for posterity.

![2015-12-07_15-00-53](https://cloud.githubusercontent.com/assets/3996934/11630037/6960c422-9cf3-11e5-96b0-8b3cc3546d31.png)

**Comment by MartinLyne** [comment]
Hmm, this seems to work: `CKEDITOR.replace(document.getElementsByClassName('content')[2])`

But not any of the simpler versions. Not sure if this is something wrong or just unclear documentation *everywhere* (including CK editor docs) feels like something isn't quite right still (jquery adapter is my preference)

**Comment by egeloen** [comment]
If you want to play with CKEditor and jQuery, you should probably enable the adapter. See https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#jquery-adapter

**Comment by MartinLyne** [comment]
Isn't that what `jquery: true` and `autoload:true` does in my initial config? Feels like there's something missing? Maybe it's loading too early, before jQUery is ready? (There's no errors in console to indicate anything failed)

**Comment by MartinLyne** [comment]
Hmm, yeah I just pasted the contents of the adapter file into my console, then the ckeditor() seems to work, so I guess it's because admin-lte js is loaded after. I'll just have to load the adapter in my base template so I can be sure when it is called. Unless you have a better idea?

**Comment by egeloen** [comment]
If you want to have full support of the js lib loading I would suggest you to disable the autoload and jquery feature and load it by yourself.
