### ISSUE TITLE
jQuery should be loaded before CKEditor jQuery adapter.

### ISSUE THREAD

**Issue by JHGitty** [egeloen/IvoryCKEditorBundle#202]
We use version ``~4.0@dev``.
CKEditor is not shown.

The browser console reports:
```
jQuery should be loaded before CKEditor jQuery adapter.
```

The output HTML contains:
```html
<script type="text/javascript" src="/bundles/ivoryckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/bundles/ivoryckeditor/adapters/jquery.js"></script>
```

We load JQuery on the end of the website. How could we fix it?

**Comment by egeloen** [comment]
This is a known limitation. As the javascript is loaded in the ckeditor type widget, the jquery library must be loaded before it. 

To fix it, you can load it in the head of the page (seems not what you want) or disable the whole ckeditor javascript loading and do it by yourself (given you the full power).

**Comment by egeloen** [comment]
Closing as there is no feedback and the solution is simply to disable  the CKEditor js loading and load the adapter by yourself at the end of the page.
