### ISSUE TITLE
how to upload files

### ISSUE THREAD

**Issue by aristos32** [egeloen/IvoryCKEditorBundle#206]
I am sure that I am missing something very obvious, but I cannot understand how to upload a photo inside the editor.
What I do:

- press 'image'
- find the file
- press send to server
- press OK
![git2](https://cloud.githubusercontent.com/assets/17019706/12741413/a84a04ba-c984-11e5-82c9-e958c10c2b2b.png)

But I get an error : 'image source URL is missing'

What else is needed? How will my route be called to debug it?

![git1](https://cloud.githubusercontent.com/assets/17019706/12741342/17c1649c-c984-11e5-824b-970f02da858a.png

**Comment by egeloen** [comment]
I'm sorry but I can't help you without more explanation. Have you followed this steps: https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/file_browse_upload.md ?

**Comment by egeloen** [comment]
I have refined the doc in #213 I hope it is more clear now... If no, please re-open an issue as for me everything is working fine and without more explanation, I can't help.

**Comment by aristos32** [comment]
Hi Eric and thanks for your reply.

My issue is: I want to upload a file in the editor, not use the gallery. So
I don't need the 'browse' parameters, right?

So I set my upload routing only:
'filebrowserUploadRoute' =>
'GeneralGeneralBundle_account_profile_question_photo_upload',
'filebrowserUploadRouteParameters' => array('user_id' => '10',
'responseType' => 'json'),
'filebrowserUploadRouteAbsolute'   => true,

But when I submit I get 'image source url is missing'.

Can you give me a configuration that will work, since I am missing
something obvious here.

Thank you!

On 22 February 2016 at 10:49, Eric GELOEN <notifications@github.com> wrote:

> I have refined the doc in #213
> <https://github.com/egeloen/IvoryCKEditorBundle/pull/213> I hope it is
> more clear now... If no, please re-open an issue as for me everything is
> working fine and without more explanation, I can't help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egeloen/IvoryCKEditorBundle/issues/206#issuecomment-187076682>
> .
>



-- 
The greatest enemy of knowledge is not ignorance, it is the illusion of
knowledge
 - Stephen Hawking

**Comment by egeloen** [comment]
If you can fork my Symfony SE from this branch (https://github.com/egeloen/symfony-standard/tree/ckeditor) and add your code to reproduce your issue, you're awesome! It will be more rapid for me to debug it otherwise I will need to boostrap all the upload and the code in a new branch to give it a try...

**Comment by aristos32** [comment]
Hi Erik.

I am not so familiar with github and I hope I did what you ask me to do.

I created a new file QuestionType in my fork root.

My issue is: I want to upload a file in the editor, not use the gallery. So
I don't need the 'browse' parameters, right?

But when I submit I get 'image source url is missing'.

Please let me know if i need to do something different.

thanks
Aristos

On 7 March 2016 at 12:52, Eric GELOEN <notifications@github.com> wrote:

> If you can fork my Symfony SE from this branch (
> https://github.com/egeloen/symfony-standard/tree/ckeditor) and add your
> code to reproduce your issue, you're awesome! It will be more rapid for me
> to debug it otherwise I will need to boostrap all the upload and the code
> in a new branch to give it a try...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egeloen/IvoryCKEditorBundle/issues/206#issuecomment-193202473>
> .
>



-- 
The greatest enemy of knowledge is not ignorance, it is the illusion of
knowledge
 - Stephen Hawking

**Comment by egeloen** [comment]
@aristos32 Nice if you have forked my repository. Can you give ma a link pointing to your branch?

**Comment by napestershine** [comment]
@aristos32  Are you looking for drag and drop kind of functionality?

**Comment by aristos32** [comment]
@napestershine yes . But still cannot upload to my server. I tried add-ons uploadimage and uploadwidget. If you can suggest a successful configuration it would be great.

@egeloen attached you can find my form/type file
[QuestionType.txt](https://github.com/egeloen/IvoryCKEditorBundle/files/199028/QuestionType.txt)

**Comment by egeloen** [comment]
So after looking to your issue, the issue you got is "normal". When you integrate an upload feature in CKEditor, the url field is not automatically populated as CKEditor does not know where you have stored your images (it can be a different server than the one used for rendering your page). 

So, knowing that, it's up to you to manage the url propagation into the url field. Take a look [here](http://docs.cksource.com/CKEditor_3.x/Developers_Guide/File_Browser_(Uploader)/Custom_File_Browser), everything is explained.

Closing as there is nothing wrong in the bundle.
