### ISSUE TITLE
The Twig extension should not depend on the Templating helper

### ISSUE THREAD

**Issue by stof** [egeloen/IvoryCKEditorBundle#209]
This dependency means it forces a dependency on the Templating component. but Symfony 2.8+ makes it possible to use Symfony without the Templating component (using the Twig_Environment directly).

**Comment by egeloen** [comment]
@stof Thanks for pointing it. I will fix it this week in a BC way.

**Comment by egeloen** [comment]
@stof I would like to unregister the twig/php renderer in a compiler pass according to the user conf. Relying on the container parameter `templating.engines` is the way to go?

**Comment by stof** [comment]
no. If you disabled the templating component entirely, this won't exist, while TwigBundle might still be there.

For the PHP engine, you can rely on it, but for the Twig extension, you should detect the availability of the ``twig`` service

**Comment by egeloen** [comment]
Thanks for the clarification!
