### ISSUE TITLE
Making IvoryCKEditorBundle an "official" Symfony bundle

### ISSUE THREAD

**Issue by javiereguiluz** [egeloen/IvoryCKEditorBundle#210]
As you can read in [this discussion](https://github.com/symfony/symfony-docs/issues/6248) we'd like to make IvoryCKEditorBundle **the official WYISWYG bundle for Symfony**.

This means that we'll publish this bundle's doc at http://symfony.com/doc/bundles/ ... but that requires to transform the documentation from Markdown to RestructuredText, as used elsewhere in Symfony Docs.

Would you agree to that change? Would you like to do that change yourselves or do you prefer if we create the pull request with the changes?

We'll also add mentions to this bundle wherever is appropriate and makes sense in the Symfony Docs. If you have any idea about where to put these mentions, please tell us.

Thanks for your help!

**Comment by egeloen** [comment]
I'm :+1: Is there something specific about the doc structure I should be aware?
