### ISSUE TITLE
Add Async support

### ISSUE THREAD

**Issue by egeloen** [egeloen/IvoryCKEditorBundle#212]
Currently, this bundle directly renders a `CKEditor.replace` or `CKEditor.inline` directly in the template inside a script tag. Knowing that, the CKEditor library must be loaded before this line otherwise we will end up with an error related to `CKEditor could not be found`.

When using jQuery, the only difference is the code is wrapped in a `jQuery(document).ready` function but we still need to load jQuery, CKEditor and the CKEditor jQuery adapter before we render the widget.

Now, I'm looking for a solution to allow to load the dependencies (jQUery, CKEditor, ...) at the end of the page (after the `CKEditor.replace`)

**Comment by egeloen** [comment]
@JHGitty Since you are the one who reported it, how would you like to see it working?

**Comment by UFOMelkor** [comment]
Perhabs something like the `form_javascript` used within the [GenemuFormBundle](https://github.com/genemu/GenemuFormBundle/blob/master/Resources/doc/template.md) and the [DatetimepickerBundle](https://github.com/stephanecollot/DatetimepickerBundle/blob/master/Resources/views/Form/jquery_layout.html.twig) might be helpfull?

**Comment by egeloen** [comment]
@UFOMelkor Thanks for the idea, I have updated the original description to give a better overview of the current state. I like the idea of a `ckeditor_javascript` tag but plenty of questions come to my mind such as:

- what about if there are multiple forms in the same page? 
- Do we rely on a global state in order to know if the library has already been loaded and no need to reload it? 
- How do we deal with form collection/prototype?

**Comment by egeloen** [comment]
Nevermind, I think I got your idea, do you suggest to always make it async by moving all the javascript stuff in the `ckeditor_javascript` twig function? If yes, one question remind to my mind:

- What about if there are multiple forms in the same page? Do we allow to pass an array of forms to this new function?
