### ISSUE TITLE
Using with jQuery Steps

### ISSUE THREAD

**Issue by ScreamZ** [egeloen/IvoryCKEditorBundle#220]
Hello buddies,

really nice job carry on, but I'm getting an issue when I try to use the plugin with http://www.jquery-steps.com

Jquery Steps is destroying one part of the DOM and then rebuild it, the thing is therefore I get Twice CKEDITOR for each textarea. Do you have an idea about how can I achieve a correct and elegant way for that ?

I tried to replay  if (CKEDITOR.instances["psychologies_create_test_psy_test_article"]) { delete CKEDITOR.instances["psychologies_create_test_psy_test_article"]; }

but didn't worked...

Thanks

**Comment by egeloen** [comment]
ping?

**Comment by egeloen** [comment]
Ok, thanks for the feedback, Do not hesitate to re-open!
