### ISSUE TITLE
Adding other config options like DTD

### ISSUE THREAD

**Issue by stokjes** [egeloen/IvoryCKEditorBundle#223]
I would like to request the possibility to manipulate settings set in the DTD for ckeditor: http://docs.ckeditor.com/#!/api/CKEDITOR.dtd. For now only the config is configurable.

**Comment by egeloen** [comment]
I'm :+1: a PR is very welcome!

**Comment by egeloen** [comment]
@stokjes Whould you interested about making a PR for that?

**Comment by egeloen** [comment]
I have started to work on this topic but I would like first to get feedback about your usecase @stokjes What would you configure on the dtd?

**Comment by stokjes** [comment]
Hi @egeloen, i'm sorry for my late response. If you like I can create an PR for that, but i currently don't have much time. I'm using the DTD to configure allowed empty elements for CKEditor, like: <span></span>.

**Comment by egeloen** [comment]
Can you share some code on how do you do it with CKEditor? Basically, how DTD is supposed to be configured. I have never used the DTD and I would like to be sure I cover as mush use cases as possible... :)

**Comment by egeloen** [comment]
@stokjes Have you try to configure the option `extraAllowedContent` which seem related to your use case. See http://docs.ckeditor.com/#!/api/CKEDITOR.config for the explanation of this configuration option.

**Comment by egeloen** [comment]
@stokjes After thinking about your issue, I don't think I will add a `DtdManager` as it seems really rare use case to update it and I have found a dead simple way to add custom javascript to all CKEditor widget. It s already supported but not documented, so, I will add it to the doc :)
