### ISSUE TITLE
Documentation on configuration?

### ISSUE THREAD

**Issue by luispabon** [egeloen/IvoryCKEditorBundle#228]
The docs don't really explain what is possible to configure via symfony config on this bundle. I know a few things are possible, but I've found that information elsewhere on the web and not on the bundle's documentation. 

A full cheatsheet on what's configurable via symfony would go a long way to alleviate this issue and give an idea of what other features the bundle might be missing.

**Comment by egeloen** [comment]
Hey!

I'm not sure how I can improve it, I have explicitely not listed all the possibilities because the config node is the exact same as http://docs.ckeditor.com/#!/api/CKEDITOR.config

So, basically, all documented CKEditor options are usable in the config node.

**Comment by egeloen** [comment]
So, my question is: How would you improve this part knowing what I just explain :)

**Comment by luispabon** [comment]
Aye, that's where I got my config from. I believe the bundle itself should have at least some sample configs, and some way to specify symfony routes for stuff like URLs (eg image browser API).

Will try cobble up a PR with basic docs first.

**Comment by egeloen** [comment]
Routes are also supported in the bundle. See http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/file-browse-upload.html#routing-options

**Comment by luispabon** [comment]
Awesome, I completely missed that. Renders this issue irrelevant, so closing now. Thank you!

**Comment by egeloen** [comment]
If you think you can improve the doc, a PR is always very welcome! :)
