### ISSUE TITLE
How to add filebrowserVideoBrowseRoute ?

### ISSUE THREAD

**Issue by raphaelriehl** [egeloen/IvoryCKEditorBundle#231]
Hello,

Is it possible to add my own filebrowser route name ?
I would like add this :

> filebrowserVideoBrowseRoute
> filebrowserVideoBrowseRouteParameters
> filebrowserVideoBrowseRouteAbsolute

In pending, I have updated the $keys array with another line ("VideoBrowse") in the function fixConfigFilebrowsers() to the file Ivory\CKEditorBundle\Templating\CKEditorHelper.php, but it's not a good practices.

Have you got another solution for me ? Thank you for advance.

**Comment by egeloen** [comment]
If there is a ``filebrowser*Browser`` parameter not supported (Video in your case), we should support it. Is ``filebrowserVideoUrl`` built-in in CKEditor?

**Comment by raphaelriehl** [comment]
I use [this plugin](http://ckeditor.com/forums/Plugins/HTML5-Video) who integrate this route name.
With CKEditor, it's possible to use custom filebrowser route name called by a custom plugin like video plugin.
I don't want you integrate directly this filebrowser route name (filebrowserVideoBrowseRoute), i will like a method to custom $keys properly.
(Sorry for my bad english, i hope my explanations are correct and understandable...)

**Comment by egeloen** [comment]
I understand your point and the use case but now, we need to figure out how to make it possible as right now it is not.

**Comment by raphaelriehl** [comment]
If i understand well your answer, ckeditor support this solution here :
http://docs.ckeditor.com/#!/guide/dev_file_manager_configuration-section-adding-file-manager-scripts-for-selected-dialog-windows

**Comment by egeloen** [comment]
Yeah, so basically a simple extension point in the config should be enought in order to configure extra keys. Would you be interested about creating a PR for that?

**Comment by egeloen** [comment]
For the record, I'm working on it so there should be something available soon :)

**Comment by egeloen** [comment]
@raphaelriehl Your issue has been fixed in the referenced PR and is part of the new release.

**Comment by raphaelriehl** [comment]
Great ! Thanks for your job and your reactivity. :)
