### ISSUE TITLE
Exception thrown in 4.0.2 when not using egeloen/form-extra-bundle

### ISSUE THREAD

**Issue by richard-fizz** [egeloen/IvoryCKEditorBundle#237]
Upon updating, I got the following error:
Unknown "form_javascript" function. Did you mean "get_javascripts" in  IvoryCKEditorBundle:Form:javascript.html.twig at line 3

I suppose this is because I'm not using egeloen/form-extra-bundle, but the composer.json suggests it shouldn't be a big issue, since it isn't a hard requirement.

**Comment by richard-fizz** [comment]
Seems to be fixed in 4.0.3... That was quick. Thanks!

**Comment by egeloen** [comment]
It has just been fixes in #236 and is part of 4.0.3 :)
