### ISSUE TITLE
How to reuse a configuration from config.yml

### ISSUE THREAD

**Issue by raphaelriehl** [egeloen/IvoryCKEditorBundle#238]
Hi,

I have a configuration saved in my config.yml.
And i would like use this configuration in a javascript file.
For example :
`CKEDITOR.replace('myId', myConfigurationArray);`

But i havent access to my configuration by this way.
Have you got any idea how to do that ?

Thanks by advance.

**Comment by egeloen** [comment]
If I understand well, you would like to manually create your CKEditor instance without using the form component?

**Comment by raphaelriehl** [comment]
In kind of, yes it's that.
I'm not sure i use the good way, but i create instance of CKEditor on demand by user (with a button).
So i have many instances of CKEditor on the same page.

**Comment by egeloen** [comment]
Are you talking about the form collection type?

**Comment by raphaelriehl** [comment]
Humm, it's probably a problem in my code.
Yes it's a form collection type but it's a little more complex : 
![Image of custom collection](http://pix.toile-libre.org/upload/original/1460447757.png)
I have many widgets on right, and i drag'n drop to the left to add widget in my page.
For all available widgets (on right), i have data-prototype and i recreate my widget after drag'n drop to the left.
In left, it's not really a collection because it's a collection set.

**Comment by egeloen** [comment]
In theory, the `data-prototype` wraps all the javascript code needed to load CKEditor. When appending the code in your page, the CKEditor should appear... Isn't it?

**Comment by raphaelriehl** [comment]
It appears because i declare CKEDITOR.replace(), else it doesn't work.
Have you got the good way to work with a collection ?
I will create a simple version of my functionnality and i wil testing where is the problem.

**Comment by egeloen** [comment]
Without seeing how you generate the right side of your form and how you handle the drag & drop, I can't really help :s

**Comment by raphaelriehl** [comment]
I will refactoring my code and i will back to you after.

**Comment by raphaelriehl** [comment]
You are right, i used the wrong method to create more CKEditor instances.
It works perfectly, the problem was my code. I close this issue.
