### ISSUE TITLE
CKEditor and CKfinder integration

### ISSUE THREAD

**Issue by robertosanval** [egeloen/IvoryCKEditorBundle#243]
I've read the doc several times but I can't get those working together.

The samples works great and my CKEditor works great too as is but I can't get the Browse button when I click on Image button.

Any help would be appreciated.

**Comment by egeloen** [comment]
I'm sorry but I have never use CKFinder... Anyway, have you followed this doc: http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/file-browse-upload.html ?

**Comment by robertosanval** [comment]
Sorry, it was my fault, I've done it. Thanks
