### ISSUE TITLE
My toolbar is empty...

### ISSUE THREAD

**Issue by devozanges** [egeloen/IvoryCKEditorBundle#246]
Hi, I set this configuration in my config.yml but my toolbar is still empty

![capture](https://cloud.githubusercontent.com/assets/15364311/16584573/17ddd250-42bd-11e6-8f6e-b13ae102aad0.JPG)

Do you have an idea ?

**Comment by egeloen** [comment]
After debugging it, it seems your items is not valid. For example, it's not `undo` but `Undo`, the first letter should be uppercase.

**Comment by devozanges** [comment]
Bonjour

L agence est en cong�s jusqu au 16 Aout.

Vos demandes seront trait�es a mon retour.

Notre service d astreinte est � votre disposition par email au supervision @ ozanges.fr en cas de problemes li�s aux services emails ou hosting / hebergement.

Merci de votre attention.

**Comment by devozanges** [comment]
"the first letter should be uppercase"
It may be helpful to remove this case restriction

**Comment by egeloen** [comment]
I reopen our issue but before we must be sure that it's not possible to have an item with a lower case frist string.

**Comment by devozanges** [comment]
(sorry but I'm not able to test yet because I have chosen another bundle as a result of this problem)

**Comment by egeloen** [comment]
@devozanges I just check and unfortunatelly, we can't automate something... I see some plugins which dont use ucfirst the name of the widget... So, it is your responsibility to upercase it since all of them are not uppercase...
