### ISSUE TITLE
constructor demands params

### ISSUE THREAD

**Issue by Haikuch** [egeloen/IvoryCKEditorBundle#248]
Should the __construct() in class CKEditorType demand parameters? How it can be  bind to a formfield in ssymfony then?

see the user on stackoverflow who has this problem:
https://stackoverflow.com/questions/38674390/using-ckeditor-in-symfony3

**Comment by egeloen** [comment]
The CKEditor type should be registered as a service in the container via https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/config/form.xml#L8-L14 so it should not be an issue.

What is your Symfony version and your CKEditor bundle version? Can you also check if the bundle is well registered in your kernel and if your cache is fresh?

**Comment by egeloen** [comment]
@Haikuch Any news?

**Comment by Haikuch** [comment]
Oh, I forgot this topic because it wasnt my personal problem. But it seems that you are right and the user didnt register it in the appkernel (see mentioned thread)
