### ISSUE TITLE
Setting language from Request::getLocale()

### ISSUE THREAD

**Issue by kgilden** [egeloen/IvoryCKEditorBundle#249]
Hey, thanks for the awesome work! We've been using the bundle for many years and it has worked great!

I was wondering if You'd ever consider having the default language of the editor coming from [`Request::getLocale()`](http://api.symfony.com/3.1/Symfony/Component/HttpFoundation/Request.html#method_getLocale)? It looks like this is the recommended way of [getting the locale](https://symfony.com/doc/current/translation/locale.html).

This would work flawlessly with rest of the translations in the sense that if a user has chosen a different locale, then the editor would also be automatically translated to the chosen language. Currently this is not very straight-forward to implement.

I'd be willing to contribute, if You think this is something the bundle should have. I'm not sure what's the best place to implement it though. Probably the locale should be merged at some point with the config. So something along the lines of

```php
if (!isset($config['language'])) {
    // Should also check if Request is actually present
    // Also, is it possible that a user of this bundle *wouldn't* want to work it that way?
    $config['language'] = $this
        ->requestStack
        ->getCurrentRequest()
        ->getLocale()
    ;
}
```

This should be done certainly before [`CKEditorRenderer::fixConfigLanguage()`](https://github.com/egeloen/IvoryCKEditorBundle/blob/dfe2e05baffe04c63f57c0216e03ddd436be0f4a/Renderer/CKEditorRenderer.php#L163..L177), but where exactly I'm not so sure.

What are Your thoughts?

**Comment by egeloen** [comment]
Thanks for your feedback! You issue is fixed by 1bd768d5c698b218e10b29782e1089a86997fa63

**Comment by kgilden** [comment]
@egeloen wow, that's awesome! Thanks!

**Comment by egeloen** [comment]
You're welcome and also lucky since I was working on this bundle at the exact same moment you posted your issue :)
