### ISSUE TITLE
symfony 3.0 deprecated line

### ISSUE THREAD

**Issue by agrisvv** [egeloen/IvoryCKEditorBundle#258]
The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead.

 (called from CKEditorRenderer.php at line 243)

```
 if (isset($config[$handler])) {
                $config[$url] = $config[$handler]($this->getRouter());
            } elseif (isset($config[$route])) {
                $config[$url] = $this->getRouter()->generate(
                    $config[$route],
                    isset($config[$routeParameters]) ? $config[$routeParameters] : array(),
                    isset($config[$routeAbsolute])
                        ? $config[$routeAbsolute]
                        : (
                            defined('Symfony\Component\Routing\Generator\UrlGeneratorInterface::ABSOLUTE_PATH')
                                ? UrlGeneratorInterface::ABSOLUTE_PATH
                                : false
                        )
                );
            }

**Comment by egeloen** [comment]
Hum... What do you mean exactly? Is `UrlGeneratorInterface::ABSOLUTE_PATH` deprecated? I ask because this code is just here for BC...

**Comment by agrisvv** [comment]
i currently use 2.8 symfony. and this come up when i use CKEditorType. ok i check bundle config, my be something old  config here.

**Comment by agrisvv** [comment]
Configure like offical documents:
http://symfony.com/doc/master/bundles/IvoryCKEditorBundle/usage/file-browse-upload.html
if i enable this option when shows deprecate
````
filebrowserBrowseRouteAbsolute:   true

**Comment by egeloen** [comment]
@agrisvv Your issue should be fixed by the referenced PR. Can you confirm? Then, I will tag a new release.

**Comment by agrisvv** [comment]
Thanks, it is fixed - no warnings :)

**Comment by egeloen** [comment]
Thanks for your feedback. 4.0.6 released!
