### ISSUE TITLE
symfony ckeditor plugin integration

### ISSUE THREAD

**Issue by famas23** [egeloen/IvoryCKEditorBundle#260]
i downloaded my ckeditor from http://ckeditor.com/builder and i extract it into "web/bundles/sonataformatter" folder.
Any one find a solution for the problem please help ????this my code:
`
    
    ivory_ck_editor:

        default_config:  news
        configs:
            news:
                
                extraPlugins: "codesnippet"
                language: %locale%
                toolbar: standard 
                stylesSet: "my_styles"
                uiColor: "#FCFCFC" #Couleur de fond de l'interface
                height: '600px' #Hauteur par défaut
                contentsCss: ['bundles/app/css/style.css']
        plugins:
            codesnippet:
                path:       "/bundles/sonataformatter/vendor/ckeditor/plugins/codesnippet/"
                filename:   "plugin.js"
`
and i got this js error message :
http://localhost/sandbox-build-2.4/web/bundles/sonataformatter/vendor/ckeditor/plugins/codesnippet/plugin.js?t=E4KA".

**Comment by egeloen** [comment]
Hum, If I understand correctly, you just want to add a custom plugin which is not shipped by default with the bundle. Am I right?

If yes, the error message seems truncated. Anyway, I think I know why it's not working. Basically, when you install a plugin, you must also install its dependencies and the dependencies of the dependencies and so on. Regarding the code snippet plugin, it requires the Widget & Dialog plugins which you have not install/configured.

**Comment by egeloen** [comment]
I see you ping everyone on all related issues :) If you have build a custom ckeditor package with the online builder, you should have everything packaged with the dependencies I guess. Am I right? If yes, then, you can use a custom CKEditor version, just need to follow this documentation: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/version.html

**Comment by egeloen** [comment]
@famas23 Does my recommendations help you?

**Comment by egeloen** [comment]
Closing as there is no feedbacks and I just regive a try to https://github.com/symfony/symfony-standard/compare/master...egeloen:ckeditor-plugin and it works as expected.
