### ISSUE TITLE
bbcode plugin does not load in ckeditor.inline

### ISSUE THREAD

**Issue by praznovskymartin** [egeloen/IvoryCKEditorBundle#264]
Hi,

I'm using "egeloen/ckeditor-bundle": "4.0.3" and want to use the ckeditor inline.
The bbcode plugin http://ckeditor.com/addon/bbcode doesn't load.

Is this a wanted feature (as the 'Source' isn't also available)?

Thanks in advance

**Comment by egeloen** [comment]
Hey @praznovskymartin !

Thanks for this report but unfortunatelly, I think this a no fix as this bunde only integrates the CKEditor full edition into Sumfony and if you want to use the "Source" button in the inline mode you need to install an extra plugin (http://ckeditor.com/addon/sourcedialog).

Basically, according to @reinmar in this post (http://ckeditor.com/comment/130740#comment-130740), the built-in "Source" plugin is not compatible with the inline mode but if you want to use it, you can by using the "Source Dialog" plugin instead:

> If you want to use the SourceDialog button, which will work with inline editor, you need the sourcedialog plugin. The Source button is added by the sourcearea plugin and won't work with inline editor. They can be easily confused, so you can check it one more.

So, if you want to do it, you need to install the "Source Dialog" plugin (see http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/plugin.html) and customize the toolbar by adding the "SourceDialog" icon (see http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/toolbar.html).
