### ISSUE TITLE
Charset issue

### ISSUE THREAD

**Issue by jakobeissler** [egeloen/IvoryCKEditorBundle#278]
Hello, I have a Symfony 3 project with iso charset and getting strange charater problems

![image](https://cloud.githubusercontent.com/assets/21203442/23365567/4d839b8a-fce2-11e6-935c-a261d6db985e.png)

Is ther any chance to change to iso?

**Comment by egeloen** [comment]
@jakobeissler Can you give me more informations such as your Symfony verson, your PHP version and your bundle version. Additionally, what is you page encoding? UTF-8?

**Comment by jakobeissler** [comment]
Sure:

- Symfony version: 3.1.8
- PHP version: 5.6
- Bundle version: 4.0
- Page encoding ISO-8859-1

php.ini encoding by default is UTF-8

**Comment by egeloen** [comment]
Hum Isn't it the issue? PHP generated UTF-8 chars whereas you specify it as ISO-8859-1 in your page. Why are you doing such strategy?

**Comment by jakobeissler** [comment]
Because our Oracle database is encoded with ISO-8859-1. Shouldn't ckeditor assume HTMLs charset?

**Comment by egeloen** [comment]
I have never played with CKEditor charset... (UTF-8 everywhere...). IMO, it should rely on your page encoding but I'm not a CKEditor expert.. Maybe there is an option in order to specify the encoding to the CKEditor. I don't know need more research...

**Comment by egeloen** [comment]
What we can try is to put a charset utf-8 on the each script tags. Update [here](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/views/Form/ckeditor_widget.html.twig) in your vendor by adding `charset="utf8"` on all script tags and give a try. Then, come back here and give me some feedbacks :)

**Comment by jakobeissler** [comment]
I tried but it didn't work.

**Comment by jakobeissler** [comment]
I have also played with this config options... no result:

```
'entities' => true,
					'entities_latin' => true,
					'basicEntities' => true,
```

**Comment by egeloen** [comment]
I need to set up a fork of the Symfony SE & give it a try...

**Comment by jakobeissler** [comment]
OK, just one thing, i've the following function in AppKernel.php because i need to force the charset for my entire site to iso-8859-1:

```
public function getCharset()
    {
        return 'ISO-8859-1';
    }
```

If i remove that function or change it to UTF-8, ckeditor works as expected.

**Comment by egeloen** [comment]
Ok thanks for this information. Anything else I should know before give it a try? Do we agree you put `<meta charset="ISO-8859-1">` in the head of your page?

**Comment by jakobeissler** [comment]
Yes that is correct. Thank you.

**Comment by egeloen** [comment]
@jakobeissler So... after almost one hour of debug, i think I got it... The issue seems coming from how CKEditor loads its translation files. 

I notice that all broken texts comes from a translation file loaded by CKEditor itself and since the page uses ISO-8895-1 as charset, I think the browser directly interprets this file with this encoding whereas the file is encoding using UTF-8... 

I have updated my nginx conf by forcing the UTF-8 encoding on this specific files (using the charset option on the entire CKEditor directory) and then everything is working fine.

**Comment by jakobeissler** [comment]
That is interesting. Just a quick question, where are the language files loaded from? I tried to edit manually the file vendor/egeloen/ckeditor-bundle/Resources/public/lang/ but no change, it seems they are loaded from a different location. 

For a different approach i could try to override the language file with correct values but i can't figure out from where they are loaded.

**Comment by egeloen** [comment]
@jakobeissler I can't find where it loads it since the javascript is minnified... but IMO, you have **copied** your file in the web directory with `bin/console assets:install` and so, updating the file in the vendor is not enought, you need to re-install assets in the web directory.

Futhermore editing file in the vendor is definitively not the way to go since when you will deploy your app, the vendor is downloaded from the source... If you wan to use your own version of CKEditor, the bundle supports it: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/version.html

**Comment by jakobeissler** [comment]
OK, i found out that the language file that is loades is: web/budnles/ivoryckeditor/lang/es.js

Is i open this file i see the text like this:

`"checkbox":"Casilla de VerificaciÃ³n"`

That doesn't look quit right does it?

**Comment by egeloen** [comment]
Hum, this is weird when I open it using https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/public/lang/es.js it looks good.

![charset](https://cloud.githubusercontent.com/assets/737992/23476534/598a7144-febb-11e6-9e80-3f61288b29be.png)

**Comment by jakobeissler** [comment]
I deleted the assets folder and installed again:

`php bin/console assets:install web`

Didn't work.

**Comment by egeloen** [comment]
When you say, I open the file and see `"checkbox":"Casilla de VerificaciÃ³n"`, where do you open it? in your browser? in your IDE?

**Comment by jakobeissler** [comment]
You are right, it is the IDE (Netbeans), opening the file in browser displays the language file ok.

**Comment by egeloen** [comment]
OK, so your IDE detects the file as ISO-8895-1... You have do something manually to get this behavior? My IDE (PHPStorm) detects the file as UTF-8 automatically. 

An other alternative is to use `dos2unix` with the `-iso` option in order to convert all CKEDitor files using ISO-8895-1.

**Comment by jakobeissler** [comment]
I set the charset in projects properties. When i deploy the symfony project to production server (linux) it doesn't work neither so has nothing to do with the IDE. I set up another ckeditor without bundle and it is working ok. I give up.

**Comment by egeloen** [comment]
Never give up :) Maybe it is related on the way I update CKEditor, where do you download CKEditor? In the bundle, I rely on this custom script: https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/bin/ckeditor-sync.sh

**Comment by jakobeissler** [comment]
It came with a template I bought (metronic). Ckeditor version is 4.4.5

**Comment by egeloen** [comment]
Can you run my script and remove the last line (dos2unix) and re-install assets in the web directory?

**Comment by jakobeissler** [comment]
Didn't work

**Comment by jakobeissler** [comment]
NO!!! wait, it DID work... I just had to clear the browsers cache.

**Comment by egeloen** [comment]
So, what does work? Removing the dos2unix line? or it works by default? or something else?

**Comment by jakobeissler** [comment]
I executed the .sh script without the last line, installed assets and it is working on my localhost and on production server. It has definitely to do with:

`find $ckeditorPath -type f -exec dos2unix {} \;`

**Comment by egeloen** [comment]
Ok, so there is something to fix. I can't remember why I needed to convert Windowd EOL to Unix ones... Need to search through the git history... Hopefully, you don't give up :)

**Comment by jakobeissler** [comment]
Ok, many many thanks for the help. Please let me know when you tag a new version with the fix so I can install with composer.

This is a great and very neccesary bundle.

**Comment by egeloen** [comment]
Here we are, your issue will be fixed by the referenced PR :)

**Comment by egeloen** [comment]
@jakobeissler I just release 5.0.1

**Comment by jakobeissler** [comment]
Thank you, it's working!!!
