### ISSUE TITLE
skin.js not found

### ISSUE THREAD

**Issue by placid2000** [egeloen/IvoryCKEditorBundle#280]
Hi, 

I'm on symfony 2.8.15 and installed IvoryCKEditorBundle 5.0.1

I'm using the office2013 skin:
`configs:
ck_editor_config:
skin: "office2013,/bundles/{bundlename}/js/ckeditor/skins/office2013/"`

And everythings works well but for unknown reasons it makes a request on a none existing resource when loading the ckeditor:
GET http://domain.lo/bundles/{bundlename}/js/ckeditor/skins/office2013/skin.js?t=H0CG 404 (Not Found)

skin.js does not exist at this location and doesn't seem to be needed since everthing works fine. But I'd like to get rid of this error..

Any idea?
Thank you

**Comment by egeloen** [comment]
@placid2000 I have give  a look to its homepage: http://ckeditor.com/addon/office2013 and it seems it is really compatible with **CKEditor 4.4 only (or at least it guarantees compatibility with this version only)** whereas the bundle relies on the very last version of CKEditor (the most up to date one). Maybe related?...

Futhermore, after some more search, http://docs.ckeditor.com/#!/guide/skin_sdk_intro specifies that the skin.js file should be there... Then, IMO, you should probably report your issue directly to the office2013 plugin.

**Comment by placid2000** [comment]
@egeloen Actually I didn't see that that version compatibility discrepancy. Thanks for the help!
