### ISSUE TITLE
Misunderstanding in the documentation (plugins)

### ISSUE THREAD

**Issue by etienne-me** [egeloen/IvoryCKEditorBundle#285]
```
plugins:
        confighelper:
            path:     "/ckeditor/plugins/confighelper/"
            filename: "plugin.js"
```

This snippet (https://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/plugin.html#register-the-plugin) doesn't work on Symfony 3.2.4, I had to specify the plugin.js in the path to get this to work properly.

```
plugins:
        confighelper:
            path:     "/ckeditor/plugins/confighelper/plugin.js"
            filename: "plugin.js"
```

Edit: Using the version 5.0.1

**Comment by egeloen** [comment]
@etienne-me Thanks for reporting this issue but I don't understand why it's not working. According to the CKEditor doc (http://docs.ckeditor.com/#!/api/CKEDITOR.plugins), `CKEditor.plugins.addExternal` should receive a plugin name, a path (directory or file) and an optional filename in case you specify a directory for the previous arg.

**Comment by etienne-me** [comment]
I cleaned the cache, reinstalled the assets and it works well now. Sorry for the inconvenience.

**Comment by egeloen** [comment]
No problem, It can help other devs later :)
