### ISSUE TITLE
Unable to find template in a Symfony Flex project 

### ISSUE THREAD

**Issue by pixocode** [egeloen/IvoryCKEditorBundle#292]
`Unable to find template "IvoryCKEditorBundle:Form:ckeditor_widget.html.twig" (looked into: templates, vendor/symfony/twig-bridge/Resources/views/Form).`

May be because the templates folder has been modified in symfony flex :/

**Comment by egeloen** [comment]
You should probably open your issue on the Symfony recipes contrib repo instead since the bug should be there.

**Comment by egeloen** [comment]
Btw, can you double check if FLex have well registered the bundle because this template is automatically registered by a compiler pass.

**Comment by egeloen** [comment]
Or maybe the notation `IvoryCKEditorBundle:Form:ckeditor_widget.html.twig` is not supported anymore with Flex (don't know)... Anyway, open an issue on Flex, guys should know what's going on better than me...

**Comment by pixocode** [comment]
I replaced `IvoryCKEditorBundle:Form:ckeditor_widget.html.twig` by `@IvoryCKEditor/Form/ckeditor_widget.html.twig` in [DependencyInjection/Compiler/ResourceCompilerPass.php](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/DependencyInjection/Compiler/ResourceCompilerPass.php) and it's work :/

[http://symfony.com/doc/master/templating/namespaced_paths.html](http://symfony.com/doc/master/templating/namespaced_paths.html)

**Comment by egeloen** [comment]
OK but AFAIR, this notation is not deprecated and should still work (I'm OK to switch to naspacced templates but only if the lowest version supported by the bundle already supports namespaced templates...)
