### ISSUE TITLE
License doubt

### ISSUE THREAD

**Issue by Xeyos88** [egeloen/IvoryCKEditorBundle#295]
I have a doubt.
How can bundle be released under MIT license if CKEditor is not released as MIT?

**Comment by egeloen** [comment]
@Xeyos88 Hum, it seems I have defintively made a mistake when licensing the bundle... Do you know what kind of license I can use to be as much permissive as possible? (an MIT like licensing which would be allowed when packing CKEditor with the code)

**Comment by Xeyos88** [comment]
I'm not familiar, but it should depend on the type of CKEditor license, if GPL also the bundle should be GPL. If instead CKEditor is MPL only CKEditor code part must remain MPL the rest can be MIT.
[MPL](https://en.wikipedia.org/wiki/Mozilla_Public_License)

**Comment by clemherreman** [comment]
I think @Xeyos88 is right, as you are currently **distributing CKEditor** (i.e. the CKEditor files are part of your repo).

You need to either change the licence, or do not embed them, but setup a way to install it when this bundle is installed.

A way to do that is to use a composer plugin that will download the CKEditor files, at the right place, when `composer {install,update}`.

**Comment by egeloen** [comment]
@clemherreman So, if I understand well, the main issue is the CKEditor files are distributed with the bundle. If I remove them / make them external, then no more licensing issue... Am I right?

@Xeyos88 CKEditor is distributed under the GPL, LGPL and MPL Open Source licenses but I would prefer keep the bundle MIT (super permissive).

**Comment by wwalc** [comment]
> @Xeyos88 CKEditor is distributed under the GPL, LGPL and MPL Open Source licenses but I would prefer keep the bundle MIT (super permissive) but before, I would like to be sure that removing the CKEditor dist files is OK to keep the bundle MIT...

Yep, that's the right way to go. See e.g. the [CKFinder bundle](https://github.com/ckfinder/ckfinder-symfony2-bundle/blob/master/LICENSE.txt) and the way how we kept the MIT license for the bundle together with a commercial software.

**Comment by egeloen** [comment]
@wwalc Thanks for your feedback, let's move this way then! :)

**Comment by egeloen** [comment]
For the record, I have a working installer but still need to work on the command output as well as testing.

**Comment by clemherreman** [comment]
> @clemherreman So, if I understand well, the main issue is the CKEditor files are distributed with the bundle. If I remove them / make them external, then no more licensing issue... Am I right?

Exactly :)
