### ISSUE TITLE
There are no commands defined in the "ckeditor" namespace.

### ISSUE THREAD

**Issue by BonnieDoug** [egeloen/IvoryCKEditorBundle#299]
Following along with the documentation found here: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/installation.html

I have currently entered the command:

`composer require egeloen/ckeditor-bundle`

 which resolves currently to 

> Using version ^5.0 for egeloen/ckeditor-bundle

After which, I enter the new package to my AppKernel and goto run the command:

`php bin/console ckeditor:install`

Unfortunately this results in this error:

>                                                                   
>   [Symfony\Component\Console\Exception\CommandNotFoundException]  
>   There are no commands defined in the "ckeditor" namespace.      
                                                                  

Using Symfony 3.3-dev, Ckeditor-bundle (5.0.3)

---

Downgrading from egeloen/ckeditor-bundle 5.0.3 to 4.0.6 did not solve anything.

**Comment by BonnieDoug** [comment]
Looking in https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/installation.rst

I noticed it had changes 14 hours ago, so I compared it to the version Composer had just download 5.0.3, which makes no mention of the `php bin/console ckeditor:install` command. 
So I switched the version from `^5.0` to `dev-master` in Composer and now the `php bin/console ckeditor:install` works perfectly.

**Comment by egeloen** [comment]
@BonnieDoug The new command (ckeditor:install) will be part of the next 6.x release (probably comming this week) but the online doc is built from master so basically, the doc already exposes this command which is not part of the current stable release (5.x).

Long story short: You can upgrade to 5.x and don't execute the ckeditor:install comand as it is only part of the upcoming 6.x release (not yet released)

**Comment by BonnieDoug** [comment]
Thats great, I'll stick with the dev-master version for the time being. The website I'm building won't be released till after 6.0 is released anyway, so no issue with it breaking in the meantime, but at least means I know I'm up to date rather than working with an older version.
