### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by filijonka** [egeloen/IvoryCKEditorBundle#303]
Hi

The documentation for this bundle doesn't follow the stable version which it should.
Apparently there are new development done on master that shouldn't be released until version 6, which is quite a big leap from current stable version.
New development shouldn't be done on master branch.
Suggestion: either release current master to new version 5.* or rollback master to latest stable version and move the new development to it's own branch and when ready to release it merge it to master.

It's not user friendly to have a documentation that isn't at the moment true.

**Comment by egeloen** [comment]
I just come back from holiday, so, sorry for the late reply... I agree that it's not user friendly and I need to talk about it with the Symfony guys as it's them which manage the doc build :)

**Comment by egeloen** [comment]
The online doc is now in sync with the code but I let the issue open as I need to get in touch with the Symfony team in order to fix it definitively...

**Comment by karael** [comment]
v6 is a bit hard to use without doc

**Comment by egeloen** [comment]
@karael The current online doc is the 6.x one.
