### ISSUE TITLE
CSS CkEditor Content

### ISSUE THREAD

**Issue by felipep** [egeloen/IvoryCKEditorBundle#31]
Nice Bundle ;)
is there any way to configure the content css of the ckeditor? 
I mean use an external css file?

**Comment by bruno-ds** [comment]
Hello,

maybe this useful information should be in the doc?
If I understood well what I read here, we can access all ckeditor conf with the config array? Ii would be great to tell this in the doc, maybe in a tooltip or other artifact for important information? (I may have missed this information in the doc)

**Comment by egeloen** [comment]
@bruno-ds Yes if you use any CKEditor options documented [here)(http://docs.ckeditor.com/#!/api/CKEDITOR.config). 

This is documented in the bundle on the config section: http://symfony.com/doc/current/bundles/IvoryCKEditorBundle/usage/config.html (very first tip block). 

Not sure how I can make it more visible in the doc... If you think you can improve it a recommendation/PR is very welcome :)

**Comment by bruno-ds** [comment]
@egeloen : I'm sorry, it was effectively in the doc.

Maybe you could add a little longer explanation in order to make it more visible, like you could say : 

> You can use any native CKEditor options. The bundle uses a variable node in its config, so, you can put basically anything in this node (but no validation are done on it, the bundle trust you).

but it is at the edge, your work is perfect, sorry.

**Comment by egeloen** [comment]
Don't be sorry, it's just a question :) I will make the block more precise tonight. Can you open an issue in order to not forget it?...
