### ISSUE TITLE
Use curl or symfony internal instead file_get_contents

### ISSUE THREAD

**Issue by jkroepke** [egeloen/IvoryCKEditorBundle#312]
Hi,

/cc @f1terit

our server is secured by a firewall. We have to go via proxy to access the internet.

By default, file_get_contents can not go over a proxy. I have to configure the stream context which is not possible for me at composer time.

https://github.com/egeloen/IvoryCKEditorBundle/blob/4d59b5467a9d1aefa2cd7d0fc239a46c17ccb0ce/Installer/CKEditorInstaller.php#L188

It's possible to use curl instead file_get_contents?

**Comment by egeloen** [comment]
Does an entry in the composer extra allowing you to configure your proxy would be enough to you?

**Comment by jkroepke** [comment]
Yeah. 

Otherwise auto detect a proxy, if the environment variable http_proxy or https_proxy is defined.

**Comment by egeloen** [comment]
Btw, what do you refer to when you say "Symfony internal"?

**Comment by jkroepke** [comment]
Symfony http client libraries.

http://symfony.com/doc/current/components/browser_kit.html

or external bundles like

https://github.com/8p/GuzzleBundle
