### ISSUE TITLE
php 7.1

### ISSUE THREAD

**Issue by grekpg** [egeloen/IvoryCKEditorBundle#321]
Why this bundle is limited to 7.0 ? 
php: ^5.6|^7.0 - 7.1 is not supported.

**Comment by egeloen** [comment]
AFAIK, `^5.6|^7.0` is equivalent to `>=5.6,<8.0`. `^` means BC by using SemVer RFC so, `7.1` should be supported.

**Comment by egeloen** [comment]
Closing, see the travis build which works on 7.1: https://travis-ci.org/egeloen/IvoryCKEditorBundle
