### ISSUE TITLE
Services will become private by default starting from Symfony 3.4 

### ISSUE THREAD

**Issue by javiereguiluz** [egeloen/IvoryCKEditorBundle#323]
Services that need to public need to explicitly marked as public starting from Symfony 3.4. See http://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default

When updating a Symfony app using this bundle to Symfony 3.4, I saw these deprecation messages:

```
User Deprecated: The "ivory_ck_editor.renderer.json_builder" service is private,
getting it from the container is deprecated since Symfony 3.2 and will fail in
4.0. You should either make the service public, or stop using the container
directly and use dependency injection instead.

User Deprecated: The "assets.packages" service is private, getting it from the
container is deprecated since Symfony 3.2 and will fail in 4.0. You should
either make the service public, or stop using the container directly and use
dependency injection instead.
```

**Comment by javiereguiluz** [comment]
I'm using this bundle in a Symfony 4 app, and I see this message:

```
An exception has been thrown during the rendering of a template
("The "ivory_ck_editor.renderer.json_builder" service or alias has
been removed or inlined when the container was compiled. You
should either make it public, or stop using the container directly
and use dependency injection instead.").
```

**Comment by cybernet** [comment]
@javiereguiluz i still don't know how did you installed it ... via composer is not working due to incompatibly with `symfony/form` ...

**Comment by thelem** [comment]
Duplicate of #329

This bundle isn't being actively developed. It has been forked by FOS, see https://github.com/FriendsOfSymfony/FOSCKEditorBundle/blob/1.x/docs/migration.rst for migration instructions.

**Comment by javiereguiluz** [comment]
Closing as a duplicate of #329.
