### ISSUE TITLE
The bundle is incompatible with Symfony4

### ISSUE THREAD

**Issue by alyamovsky** [egeloen/IvoryCKEditorBundle#343]
Hi there! Due to upper version bounds for such dependencies as symfony/framework-bundle, symfony/dependency-injection, twig etc. the bundle is currently incompatible with Symfony4 projects. Are you planning to update it?

**Comment by szymach** [comment]
Duplicate of #329

**Comment by pulzarraider** [comment]
See https://symfony.com/blog/finding-a-new-home-for-ivoryckeditorbundle

**Comment by mverijdt** [comment]
the new home was found: [Friends Of Symfony - CK Editor Bundle](https://github.com/FriendsOfSymfony/FOSCKEditorBundle)

It is compatible now, this issue can be closed
