### ISSUE TITLE
Not storing value in sonata_type_collection

### ISSUE THREAD

**Issue by devpetrov** [egeloen/IvoryCKEditorBundle#47]
Hi, 

When using the ckeditor in sonata_type_collection pressing the "Add new" button adds a row where one of the fields is of type ckeditor. Write something in all the fields and then press again "Add new". The value entered in the ckeditor field in the fist row is lost. The values for the rest of the fields are kept.
![ckeditor_not_storing_value](https://f.cloud.github.com/assets/841636/813008/65f79f40-eef9-11e2-9be7-ec252c74b491.png)

**Comment by MelnikDima** [comment]
->add('your_field_name', CKEditorType::class, array(
				'config_name' => 'default',
				'input_sync' => true,/// this synchronizes texarea on add new row
			))
